#!/bin/bash


CMAKE_FILES="./CMakeFiles"

if [[ -d "$CMAKE_FILES" ]]; then
   echo "cmake files found" 
else
    echo "CMakeFiles not found. running cmake"
    cmake .
fi


if [ -z "$1" ]; then
    echo "build and run"
    echo "Usage: $0 <executable_name>"
    exit 1
fi

EXECUTABLE_NAME=$1

clear

MESSAGE=$(cat message.txt) 

echo -e "${MESSAGE} ${EXECUTABLE_NAME}"

cmake --build .


chmod u+x "bin/${EXECUTABLE_NAME}"

echo ""
echo "running App"
"./bin/${EXECUTABLE_NAME}"

