#!/bin/bash

# Check if an executable name is provided as an argument
if [ -z "$1" ]; then
    echo "build and run"
    echo "Usage: $0 <executable_name>"
    exit 1
fi

EXECUTABLE_NAME=$1

# Build the project
echo "Building project"
cmake .
cmake --build .

# Make the specified executable runnable
chmod u+x "bin/${EXECUTABLE_NAME}"

# Run the executable
echo ""
echo "running App"
"./bin/${EXECUTABLE_NAME}"

