#pragma once
#include <iostream>
#include <vector>
#include <string>
#include <memory>
#include <random>
#include <chrono>
#include <sstream>
#include <iomanip>
#include <thread>
#include <ncurses.h>
#include <sys/param.h>
#include <locale.h>
